### ISSUE TITLE
Publish to central script

### ISSUE THREAD

**Issue by sleeyax** [sleeyax/stremio-addon#4]
Would be nice to have this, but might be unnecessary if it requires a large dependency.

**Comment by jaruba** [comment]
Do you mean publish the addon to Stremio's catalog here?

If so, it can be done with no dependencies:
https://github.com/Stremio/stremio-publish-addon/blob/master/script.js#L4-L28

(this code is from: [publish addon website](https://stremio.github.io/stremio-publish-addon/))

**Comment by sleeyax** [comment]
I mean a function or script to publish to the catalog like [publishToCentral.js](https://github.com/Stremio/stremio-addon-sdk/blob/master/src/publishToCentral.js)

But there's no built-in HTTP package in rust. That means I have a decision to make:

- install a http client like [http](https://crates.io/crates/http), [reqwest](https://crates.io/crates/reqwest) or [surf](https://crates.io/crates/surf)
- ~~write a client from scratch~~ (obviously too much work and unsafe, especially the crypto part in order for HTTPS to work)
- move from tide to [hyper](https://crates.io/crates/hyper) after all.

At the moment I think I'll stick to tide and try [surf](https://crates.io/crates/surf) to make the request. I prefer to keep the SDK as small as possible and hyper alone is 0.13MB already, while surf is just 43.13 kB.

**Comment by sleeyax** [comment]
Plans have changed, [I'm using hyper](https://github.com/sleeyax/stremio-addon-sdk/issues/7) now and thus the built-in http client can be used for this.

**Comment by sleeyax** [comment]
I'm experimenting with Hyper's HTTP client to make a `publish_to_central` method (similar to the official SDK's `publishToCentral`) in [this branch](https://github.com/sleeyax/stremio-addon-sdk/tree/publisher). It requires an extra dependency in order to get HTTPS to work and it doesn't play well with the other dependencies so far, so I might as well scrap the idea in the future.

For now a link to the publish addon website will be provided in the README.

**Comment by jaruba** [comment]
> For now a link to the publish addon website will be provided in the README.

That should be enough tbh..

**Comment by sleeyax** [comment]
> 
> 
> > For now a link to the publish addon website will be provided in the README.
> 
> That should be enough tbh..

Yes, you're right. I was overdoing it a bit heh.
