### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by sleeyax** [sleeyax/stremio-addon#6]
Find and test a free Rust web hosting service. Options:

- [x] now.sh (zeit.co) community Rust builder
- [x] heroku
- ~rust runtime for AWS lambda~ (now.sh already uses this in the backend)
- IPFS

**Comment by sleeyax** [comment]
Support for now.sh is on the works in the [now](https://github.com/sleeyax/stremio-addon-sdk/tree/now) branch

Update: done and merged with master.

**Comment by MartinKavik** [comment]
Heroku works with this [buildpack](https://github.com/emk/heroku-buildpack-rust) and this config:
```rust
    let options = ServerOptions {
        cache_max_age: 24 * 3600 * 7, // cache all responses for 7 days
        port: env::var("PORT").ok().and_then(|port| port.parse().ok())
            .unwrap_or(1337),
        ip: Ipv4Addr::new(0, 0, 0, 0).into(),
    };
    serve_http(interface, options);
```
(The most important is the port - Heroku assigns it dynamically and it's often a higher number.)

`Procfile` can look like this one:
```
web: ./target/release/addon_example
```

(Tested with this PR - https://github.com/sleeyax/stremio-addon-sdk/pull/10)
